In [3]:
a =  1
a

1

In [5]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [7]:
def square(a):
    """a의 제곱을 반환"""
    return a**2

In [19]:
for i in range(1, 4):
    print(i, square(i))

1 1
2 4
3 9


# 2.Numpy

In [3]:
import numpy as np
np.__version__

'1.26.4'

In [10]:
result = 0
result

0

In [12]:
result = "hello"
result

'hello'

In [15]:
c = np.zeros((2,3))
c, c.shape

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 (2, 3))

In [17]:
d = np.full((2,3), -1)
d

array([[-1, -1, -1],
       [-1, -1, -1]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> 데이터 타입을 np로만들기위함

In [21]:
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

> x값을 만들기 위해 자주 사용(시작, 끝, 나눌 개수)

In [28]:
color_image = np.random.random((32, 3, 224, 224))
color_image.shape, color_image.size

((32, 3, 224, 224), 4816896)

> normal은 정규분포형, random은 유니폼형으로 나옴

In [31]:
color_image2 = np.random.normal(0, 1, (32, 3, 224, 224))

# 배열 속성 지정

In [38]:
np.random.seed(0)

x1 = np.random.randint(10, size=6) # 1차원 배열
x2 = np.random.randint(10, size=(3, 4)) #2차원배열
x3 = np.random.randint(10, size=(3, 4, 5)) #3차원배열

In [40]:
print("x3 ndim : ", x3.ndim)
print("x3 shape : ", x3.shape)
print("x3 size : ", x3.size)
print("dtype : ", x3.dtype)

x3 ndim :  3
x3 shape :  (3, 4, 5)
x3 size :  60
dtype :  int32


In [41]:
x1

array([5, 0, 3, 3, 7, 9])

In [44]:
x1[-1]

9